// 这是整个网站的根布局文件
// 所有页面都会被包裹在这个布局里，就像一个"外壳"
// 在这里设置的内容（字体、全局样式等）会应用到所有页面

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// 加载 Geist 无衬线字体（用于正文）
// variable 是 CSS 变量名，subsets 指定字符集（latin = 拉丁字母）
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// 加载 Geist Mono 等宽字体（用于代码展示）
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// metadata：网站的元数据，会显示在浏览器标签页和搜索引擎结果里
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout：根布局组件
// children 是子页面的内容，会被插入到 <body> 里
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // lang="en" 告诉浏览器页面语言（可以改成 "zh-CN"）
    // className 里应用了字体变量和 antialiased（字体平滑）
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* min-h-full 确保页面至少占满整个屏幕高度 */}
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
